kind: 'BuildConfig'
apiVersion: 'v1'
metadata:
  name: 'jwt-token-creation-api'
  namespace: cicd
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/tmlconnected/AIP_JWT_TOKEN.git'
    sourceSecret:
      name: github-secret-ka  
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: PROJECT
        value: dev-esb
      jenkinsfilePath: 'Jenkinsfile'
